org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.overridePathCheck=true
org.gradle.caching=true
org.gradle.parallel=true
# Избегаем ошибки R8 "SharedPreferencesPlugin is defined multiple times"
android.enableR8.fullMode=false
